name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, mbstring
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict

      # ライブラリ想定: lock を使わず update で検証（lock をコミットする運用なら install に戻してください）
      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Install deps (library style: update)
        run: composer update --no-interaction --prefer-dist --no-progress

      - name: CS (dry-run)
        run: composer check:cs
        continue-on-error: true

      - name: Static Analysis
        run: composer analyse

      - name: PHPUnit
        run: composer test
